In [2]:
## Imports
import os
os.environ["R_HOME"] = r"C:\Program Files\R\R-4.0.3"
os.environ["PATH"]   = r"C:\Program Files\R\R-4.0.3\bin\x64" + ";" + os.environ["PATH"]
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.cm as colmap
import seaborn as sns
from set_tex_fonts import set_latex_font
import pingouin as pg
import motor_control_tools.figures as figures
import motor_control_tools.signal as signal
import manage_expe as me
from motor_control_tools.visual_tools import mean_profiles
import re
import pickle
from scipy.stats import pearsonr
import analyses

****
Working on Transp_2DDL data
****

c:\users\nairo\appdata\local\programs\python\python38\lib\site-packages\outdated\utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.3.12, the latest is 0.5.3.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(
c:\users\nairo\appdata\local\programs\python\python38\lib\site-packages\outdated\utils.py:14: OutdatedPackageWarning: The package outdated is out of date. Your version is 0.2.1, the latest is 0.2.2.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [4]:
## Load population kinematics
all_qtm_data = pd.read_csv("./all_params/Transp_2DDL_index_cut-off-rel-5.csv", encoding = "ISO-8859-1", engine='python')
all_qtm_data = all_qtm_data.groupby(['subject','condition','target','direction']).mean().reset_index()
all_qtm_data = all_qtm_data.drop(columns = ['subject','condition','movement','target','direction','block','PD','tPD','mD','PV/mV','rtPA/rtPV','tPA','smooth','A','tPV','valid'])
all_qtm_data

,MD,PV,rtPV,mV,PA,rtPA,mA,curve
0,2.17750,0.339581,0.393112,0.151942,0.737855,0.176364,0.389352,0.055706
1,1.96500,0.395672,0.296022,0.203141,1.560156,0.106827,0.763681,0.063462
2,2.36125,0.292780,0.314786,0.155288,0.802741,0.141197,0.473876,0.060350
3,1.90125,0.418001,0.313330,0.207135,1.611213,0.150352,0.832136,0.059591
4,1.91750,0.451707,0.205734,0.212044,1.932878,0.118574,1.153504,0.044741
...,...,...,...,...,...,...,...,...
555,1.26875,0.536890,0.532942,0.295111,1.347226,0.208391,0.766910,0.045251
556,1.80000,0.479633,0.335257,0.245210,1.470813,0.167282,0.782314,0.037026
557,1.23000,0.615294,0.509837,0.345459,1.523412,0.245513,0.946960,0.035636
558,1.87125,0.526013,0.337103,0.293876,1.526321,0.137295,0.822936,0.041349
559,1.38750,0.676460,0.477369,0.378985,1.669163,0.229614,0.991326,0.051893

In [5]:
pg.normality(all_qtm_data)

              W          pval  normal
MD     0.809551  3.615216e-25   False
PV     0.923982  3.276472e-16   False
rtPV   0.995161  7.719606e-02    True
mV     0.931841  2.749305e-15   False
PA     0.831696  7.707526e-24   False
rtPA   0.947965  3.952465e-13   False
mA     0.818734  1.241675e-24   False
curve  0.809478  3.580376e-25   False